name: Call a reusable workflow

on:
  push
  
jobs:
  call-workflow:
    uses: mluzcabrera/reusableworkflow/.github/workflows/workflow-A.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: mluzcabrera/reusableworkflow/.github/workflows/workflow-B.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
